version: '3'

services:
  web:
    container_name: web
    command: sh ./entrypoint.sh
    build:
      context: ./innotter
    volumes:
      - ./innotter:/app
    ports:
      - "8001:8000"
    networks:
      - innotter
    depends_on:
      - innotter_db
  innotter_db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - innotter/.env
    networks:
      - innotter
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
networks:
  innotter:
    external: true
