version: '3'

services:
  web:
    container_name: web
    command: sh ./entrypoint.sh
    build:
      context: ./innotter
    ports:
      - "8001:8000"
    depends_on:
      - innotter_db
    volumes:
      - ./innotter:/app
    networks:
      - innotter
  innotter_db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - innotter/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - innotter
volumes:
  postgres_data:
networks:
  innotter:
    external: true
