version: '3'

services:
  web:
    container_name: web
    command: sh ./entrypoint.sh
    build:
      context: ./innotter
    volumes:
      - ./innotter:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    env_file:
      - innotter/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data:
