# Generated by Django 4.2.7 on 2023-11-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0003_alter_page_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="page",
            name="owner_group_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
