# Generated by Django 4.2.7 on 2023-11-11 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0008_rename_post_followers_page"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="page",
            options={"ordering": ["updated_at"]},
        ),
    ]
