# Generated by Django 4.2.7 on 2023-11-11 07:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("post", "0003_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["updated_at"]},
        ),
    ]
